package com.giiso.submmited.http;

/**
 * Created by Administrator on 2017/9/11.
 */

public class HttpContext {
    public final static String IMEI = "imei";
    public final static String MARKETID = "marketid";
    public final static String BRAND = "brand";
    public final static String EXPECTSTARTTIME = "expectStartTime";
    public final static String EXPECTFINISHTIME = "expectFinishTime";
    public final static String USERID = "userId";
    public final static String PWD = "pwd";
    public final static String PHONEMODEL = "phoneModel";
    public final static String OS = "os";
    public final static String OS_VERSION = "osVersion";
    public final static String REALFINISHTIME = "realFinishTime";
    public final static String TASKTIME = "taskTime";
    public final static String PERCENTCOMPLETE = "percentComplete";
    public final static String PLATFORM= "platForm";
    public final static String OFFSET= "offset";
    public final static String PAGENUM= "pageNum";
    public final static String KEY_WORD= "keyword";
    public final static String FIELD= "field";
    public final static String VERSION= "version";
    public final static String APP_NAME= "app_name";
    public final static String APPNAME= "appName";
    public final static String TID= "tid";
    public final static String T_ID= "tId";
    public final static String CHECKCODE= "checkCode";
    public final static String OTHERCODE= "otherCode";
    public final static String UID= "uid";
    public final static String OPENID= "openId";
    public final static String MOBILE= "mobile";
    public final static String HEADIMGURL= "headImgUrl";
    public final static String NICKNAME= "nickName";
    public final static String DESCRIPTION= "description";
    public final static String P_TYPE = "pType";
    public final static String SEX= "sex";
    public final static String BIRTHDY= "birthday";
    public final static String HEADIMG= "headImg";
    public final static String TYPENAME= "typeName";
    public final static String CLIENTID= "clientid";
    public final static String PVCCODE= "pvccode";
    public final static String AGENTID= "agentid";
    public final static String CHANNELIDS= "channelIds";
    public final static String CHANNELID= "channelId";
    public final static String PARENTNAME= "parentName";
    public final static String AREANAME= "areaName";
    public final static String PROVINCE= "province";
    public final static String PROJECT_ID = "projectId";
    public final static String CITY= "City";
    public final static String AREA= "area";
    public final static String STREET= "street";
    public final static String LONGITUDE= "longitude";
    public final static String LATITUDE= "latitude";
    public final static String IMGCHECKCODE= "imgCheckCode";
    public final static String MOBILECHECKCODE= "mobileCheckCode";
    public final static String CHANNELNAME= "channelName";
    public final static String PASSWORD = "password";
    public final static String OLDPASSWORD = "oldPassword";
    public final static String NEWPASSWORD = "newPassword";
    public final static String OP= "op";
    public final static String PAGESIZE= "pageSize";
    public final static String DAKAID= "dakaId";
    public final static String NEWS_ID= "newsId";
    public final static String DEV_TYPE = "devType";
    public final static String COMMENT_ID= "commentId";
    public final static String NICK_NAME= "nikeName";
    public final static String COMMENT_CONTENT= "comment";
    public final static String IP_ADDRESS= "IP";
    public final static String DYNAMICID= "dynamicId";
    public final static String CREATE_TIME= "createTime";
    public final static String CREATEID = "createId";
    public final static String TOPIC_CACHE= "topic_cache";
    public final static String TOKEN= "token";
    public final static String CONTENT= "content";
    public final static String COMMENT= "comment";
    public final static String VIDEOID= "videoId";
    public final static String TITLE= "title";
    public final static String ID= "id";
    public final static String AID= "aid";
    public final static String IMAGEURL= "imageUrl";
    public final static String SOURCEOF= "sourceOf";
    public final static String PUBLISHTIME= "publishTime";
    public final static String CARDID= "cardId";
    public final static String CARD_URL= "cardUrl";
    public final static String NAME= "name";
    public final static String HEAD_IMAGE_URL= "headImgUrl";
    public final static String ORIGIN_PHONE= "originPhone";
    public final static String ISTYPE= "isType";
    public final static String FROM= "from";
    public final static String VID = "vid";
    public final static String COLLECT_TIME= "time";
    public final static String COLLECT_URL= "url";
    public final static String TIMESTAMP= "timestamp";
    public final static String STARTTIME = "startTime";
    public final static String ENDTIME = "endTime";
    public final static String SIGN= "sign";
    public final static String COMMUNITYID= "communityId";
    public final static String DEVICE_ID = "deviceId";
    public final static String AMOUNT = "amount";
    public final static String PAYTYPE = "payType";
    public final static String TYPE = "type";
    public final static String TYPESTATUS = "typeStatus";
    public final static String SOURCEID = "sourceId";
    public final static String SOURCENAME = "sourceName";
    public final static String IMGURL = "imgUrl";
    public final static String STATUS = "status";
    public final static String ACTION = "action";
    public final static String MEMBERID = "memberId";
    public final static String ACTIVITYID = "activityId";
    public final static String ACTIVESTARTTIME = "activeStartTime";
    public final static String ACTIVEENDTIME = "activeEndTime";
    public final static String REGISTERTIME = "registerTime";
    public final static String PLACE = "place";
    public final static String CLASSID = "classId";
    public final static String ADNUM = "adNum";
    public final static String CHATTYPE = "chatType";
    public final static String AUDIOURL = "audioUrl";
    public final static String DURATION = "duration";
    public final static String REASON = "reason";

    public final static String MESSAGE = "message";
    public final static String LIVE_ID = "liveId";
    public final static String IP = "ip";
    public final static String LIMIT = "limit";
    public final static String LAST_DATA_TIME = "lastDataTime";
    public final static String THRESHOLD = "threshold";
    public final static String SIZE = "size";
    public final static String PLATCODE = "platCode";
    public final static String USERNAME = "userName";
    public final static String AVATARURL = "avatarUrl";
    public final static String VERIFICATION = "code";
    public final static String FINANCE = "finance";
    public final static String SHOWINTEGRAL = "showIntegral";
    public final static String NID = "nid";
    public final static String FID = "fid";
    public final static String SHOW = "show";
    public final static String SHOW_ID = "showId";
    public final static String CODE_STRING = "code";//新增
    public final static String BUCKET_NAME = "allcity-pic";
    public final static String OBJECT_KEY = "idcard_img/";
    public final static String HEAD_IMG_KEY = "head_img/";
    public final static String COMMUNITY_IMG_KEY = "community_pic/";
    public final static String DAKA_DYNAMIC_PIC = "daka_dynamic_pic/";
    public final static String DAKA_DYNAMIC_SOUND = "dynamic_sound/";
    public final static String JB_QRCODE = "jing1";

    public final static String NEWS_TYPE = "0";// type 0资讯 1视频
    public final static String VIDEO_TYPE = "1";
    public final static String SEARCH_TYPE = "home";//由首页进入到搜索结果页面
    public final static int CACHE_PAGE_NUM = 10;//推荐页缓存数据数
    public final static int CACHE_COMMON_NUM = 10;//普通页缓存数据数
    public final static String QRCODE_INVALID = "QRCODE_INVALID";
    public final static String NOT_DAKA = "NOT_DAKA";

}